### DISCUSSION TITLE
How can I add a Home menu?

### DISCUSSION THREAD

**Discussion by bobrocke** [mansoorbarri/roadster#77] [General]
I'd like to add a link in the top menu bar to the Home page. How can I do that since there is no home.md to add `menu: main` to? Maybe something like `[Params] Menus main: Home "/"`?

**Comment by mansoorbarri** [comment]
use this syntax: 
```toml
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
  ```
  
  add the `[manu]` after or before the `[params]`
