### ISSUE TITLE
[Docs] Choose one standard configuration format

### ISSUE THREAD

**Issue by stoic-hugo** [mansoorbarri/roadster#21]
For example, in the [customization docs](https://roadster-hugo.pages.dev/docs/customization/), there is a mixture of TOML and YAML. I suggest sticking to one format (TOML).

**Comment by mansoorbarri** [comment]
agree, feel free to make changes and open a PR. I am currently going through the docs and will change the config to TOML

**Comment by stoic-hugo** [comment]
You just need to change this part in the customization docs 
```
thumbnail:
  src: "img/placeholder.png"
  visibility:
    - list
    - post
  ```
